### ISSUE TITLE
Anything Special Rails 5.0.01 Ruby 2.3.1

### ISSUE THREAD

**Issue by adsr13** [IcaliaLabs/furatto-rails-start-kit#4]
Do I need to do anything special to this app to get it to run on Ruby 2.3.1 and Rails 5.0.0.1?
Thanks in advance!

**Comment by adsr13** [comment]
I went ahead and attempted to install Rails 4.0.3  gem install rails 4.0.3 installed 4.0.2 instead.
Going further I went ahead and tried to install ruby-2.0.0, and this was the result:

cdb:furatto-rails-start-kit adsr13$ rvm install ruby-2.0.0
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.0.0-p648.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Updating certificates in '/usr/local/etc/openssl/cert.pem'.
Requirements installation successful.
Installing Ruby from source to: /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648, this may take a while depending on your cpu(s)...
ruby-2.0.0-p648 - #downloading ruby-2.0.0-p648, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-  0 10.2M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:- 14 10.2M   14 1530k    0     0  1054k      0  0:00:09  0:00:01  0:00:0 24 10.2M   24 2574k    0     0  1008k      0  0:00:10  0:00:02  0:00:0 30 10.2M   30 3214k    0     0   961k      0  0:00:10  0:00:03  0:00:0 43 10.2M   43 4590k    0     0  1058k      0  0:00:09  0:00:04  0:00:0 83 10.2M   83 8782k    0     0  1646k      0  0:00:06  0:00:05  0:00:0100 10.2M  100 10.2M    0     0  1836k      0  0:00:05  0:00:05 --:--:-- 2101k
ruby-2.0.0-p648 - #extracting ruby-2.0.0-p648 to /Users/adsr13/.rvm/src/ruby-2.0.0-p648....
ruby-2.0.0-p648 - #applying patch /Users/adsr13/.rvm/patches/ruby/ssl_no_v3.patch.
ruby-2.0.0-p648 - #configuring........................................|
ruby-2.0.0-p648 - #post-configuration.
ruby-2.0.0-p648 - #compiling..........................................-
ruby-2.0.0-p648 - #installing..............
ruby-2.0.0-p648 - #making binaries executable..
ruby-2.0.0-p648 - #downloading rubygems-2.4.8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-100  437k  100  437k    0     0  1486k      0 --:--:-- --:--:-- --:--:-- 1492k
ruby-2.0.0-p648 - #extracting rubygems-2.4.8....
ruby-2.0.0-p648 - #removing old rubygems.........
ruby-2.0.0-p648 - #installing rubygems-2.4.8..
Error running 'env GEM_HOME=/Users/adsr13/.rvm/gems/ruby-2.0.0-p648@global GEM_PATH= /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -d /Users/adsr13/.rvm/src/rubygems-2.4.8/setup.rb --no-document',
showing last 15 lines of /Users/adsr13/.rvm/log/1479196227_ruby-2.0.0-p648/rubygems.install.log
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/adsr13/.rvm/gems/ruby-2.3.1/bin:/Users/adsr13/.rvm/gems/ruby-2.3.1@global/bin:/Users/adsr13/.rvm/rubies/ruby-2.3.1/bin:/Users/adsr13/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
GEM_PATH=/Users/adsr13/.rvm/gems/ruby-2.3.1:/Users/adsr13/.rvm/gems/ruby-2.3.1@global
command(7): env GEM_HOME=/Users/adsr13/.rvm/gems/ruby-2.0.0-p648@global GEM_PATH= /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -d /Users/adsr13/.rvm/src/rubygems-2.4.8/setup.rb --no-document
Exception `LoadError' at /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/rubygems.rb:1087 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/rubygems.rb:1096 - cannot load such file -- rubygems/defaults/ruby
/Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): mapping values are not allowed in this context at line 1 column 22 (Psych::SyntaxError)
	from /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /Users/adsr13/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Users/adsr13/.rvm/src/rubygems-2.4.8/lib/rubygems/config_file.rb:333:in `load_file'
	from /Users/adsr13/.rvm/src/rubygems-2.4.8/lib/rubygems/config_file.rb:198:in `initialize'
	from /Users/adsr13/.rvm/src/rubygems-2.4.8/lib/rubygems/gem_runner.rb:74:in `new'
	from /Users/adsr13/.rvm/src/rubygems-2.4.8/lib/rubygems/gem_runner.rb:74:in `do_configuration'
	from /Users/adsr13/.rvm/src/rubygems-2.4.8/lib/rubygems/gem_runner.rb:39:in `run'
	from setup.rb:45:in `<main>'

PLEASE ADVISE? Thanks in advance.

**Comment by kurenn** [comment]
Were you able to install ruby 2.0.0?

**Comment by adsr13** [comment]
not sure what you mean, can you point to thread I posted my question in?
Thank you my furatto work as come to a hault.

**Comment by kurenn** [comment]
For what you posted, you were trying to install ruby 2.0.0 through rvm, was that installation successful?

**Comment by adsr13** [comment]
It was but furatto was not working everything seems outdated?

**Comment by kurenn** [comment]
Not sure if I understand the message, but yeah the gem is outdated, did you manage to make it work?

**Comment by adsr13** [comment]
I'll try again I kinda let it dead cuz I didn't here from anyone I thought
the app was unsupprted, but I was very interested in it, and dev shop it
was made from. Next I'll look at it again, cuz its vague to me too.

**Comment by kurenn** [comment]
Yeah, please let me know if I can be of any help!

**Comment by adsr13** [comment]
sweet. I would really like to use furatto in my next projects stack for sure... any tutorials on furatto, like on youtube or where ever?

**Comment by kurenn** [comment]
Not right now, but we have now evolved the framework into this https://github.com/IcaliaLabs/alom a much simpler a leaner version!

**Comment by adsr13** [comment]
I just put a fork in it! lol

**Comment by kurenn** [comment]
Sweet!
